// Code generated by "stringer -type=ARM64Flag,X86_64Flag,PerProcessFlag,SystemWideFlag -linecomment -output funcvariant_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ARM64FlagDefault-0]
	_ = x[ARM64FlagFLAGM-1]
	_ = x[ARM64FlagFLAGM2-2]
	_ = x[ARM64FlagFHM-3]
	_ = x[ARM64FlagDOTPROD-4]
	_ = x[ARM64FlagSHA3-5]
	_ = x[ARM64FlagRDM-6]
	_ = x[ARM64FlagLSE-7]
	_ = x[ARM64FlagSHA256-8]
	_ = x[ARM64FlagSHA512-9]
	_ = x[ARM64FlagSHA1-10]
	_ = x[ARM64FlagAES-11]
	_ = x[ARM64FlagPMULL-12]
	_ = x[ARM64FlagSPECRES-13]
	_ = x[ARM64FlagSB-14]
	_ = x[ARM64FlagFRINTTS-15]
	_ = x[ARM64FlagLRCPC-16]
	_ = x[ARM64FlagLRCPC2-17]
	_ = x[ARM64FlagFCMA-18]
	_ = x[ARM64FlagJSCVT-19]
	_ = x[ARM64FlagPAUTH-20]
	_ = x[ARM64FlagPAUTH2-21]
	_ = x[ARM64FlagFPAC-22]
	_ = x[ARM64FlagDPB-23]
	_ = x[ARM64FlagDPB2-24]
	_ = x[ARM64FlagBF16-25]
	_ = x[ARM64FlagI8MM-26]
	_ = x[ARM64FlagWFXT-27]
	_ = x[ARM64FlagRPRES-28]
	_ = x[ARM64FlagECV-29]
	_ = x[ARM64FlagAFP-30]
	_ = x[ARM64FlagLSE2-31]
	_ = x[ARM64FlagCSV2-32]
	_ = x[ARM64FlagCVS3-33]
	_ = x[ARM64FlagDIT-34]
	_ = x[ARM64FlagFP16-35]
	_ = x[ARM64FlagSSBS-36]
	_ = x[ARM64FlagBTI-37]
	_ = x[ARM64FlagSME-44]
	_ = x[ARM64FlagSME2-45]
	_ = x[ARM64FlagSMEF64F64-46]
	_ = x[ARM64FlagSMEI16I64-47]
	_ = x[ARM64FlagSMEF32F32-48]
	_ = x[ARM64FlagSMEBI32I32-49]
	_ = x[ARM64FlagSMEB16F32-50]
	_ = x[ARM64FlagSMEF16F32-51]
	_ = x[ARM64FlagSMEI8I32-52]
	_ = x[ARM64FlagSMEI16I32-53]
	_ = x[ARM64FlagADVSIMD-54]
	_ = x[ARM64FlagADVSIMDHPFP-55]
	_ = x[ARM64FlagCRC32-56]
}

const (
	_ARM64Flag_name_0 = "defaultflagmflagm2fhmdotprodsha3rdmlsesha256sha512sha1aespmullspecressbfrinttslrcpclrcpc2fcmajscvtPAuthPAuth2fpacdpbdpb2bf16i8mmWFxTrpresecvafplse2csv2cvs3ditfp16ssbsbti"
	_ARM64Flag_name_1 = "smesme2smef64f64smei16i64smef32f32smebi32i32smeb16f32smef16f32smei8i32smei16i32AdvSIMDAdvSIMDHpfpcrc32"
)

var (
	_ARM64Flag_index_0 = [...]uint8{0, 7, 12, 18, 21, 28, 32, 35, 38, 44, 50, 54, 57, 62, 69, 71, 78, 83, 89, 93, 98, 103, 109, 113, 116, 120, 124, 128, 132, 137, 140, 143, 147, 151, 155, 158, 162, 166, 169}
	_ARM64Flag_index_1 = [...]uint8{0, 3, 7, 16, 25, 34, 44, 53, 62, 70, 79, 86, 97, 102}
)

func (i ARM64Flag) String() string {
	switch {
	case i <= 37:
		return _ARM64Flag_name_0[_ARM64Flag_index_0[i]:_ARM64Flag_index_0[i+1]]
	case 44 <= i && i <= 56:
		i -= 44
		return _ARM64Flag_name_1[_ARM64Flag_index_1[i]:_ARM64Flag_index_1[i+1]]
	default:
		return "ARM64Flag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[X86_64FlagDefault-0]
	_ = x[X86_64FlagSSE41-1]
	_ = x[X86_64FlagFMA-2]
	_ = x[X86_64FlagAVX-3]
	_ = x[X86_64FlagAVX2-4]
	_ = x[X86_64FlagAVX512F-5]
	_ = x[X86_64FlagAVX512BW-6]
	_ = x[X86_64FlagBMI1-7]
	_ = x[X86_64FlagROSETTA-8]
	_ = x[X86_64FlagHASWELL-9]
	_ = x[X86_64FlagIVYBRIDGE-10]
	_ = x[X86_64FlagNEHALEM-11]
}

const _X86_64Flag_name = "defaultsse41fmaavxavx2avx512favx512bwbmi1rosettahaswellivybridgenehalem"

var _X86_64Flag_index = [...]uint8{0, 7, 12, 15, 18, 22, 29, 37, 41, 48, 55, 64, 71}

func (i X86_64Flag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_X86_64Flag_index)-1 {
		return "X86_64Flag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _X86_64Flag_name[_X86_64Flag_index[idx]:_X86_64Flag_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PerProcessFlagDefault-0]
	_ = x[PerProcessFlagTranslated-1]
	_ = x[PerProcessFlagMTE-2]
	_ = x[PerProcessFlagNoOverread-3]
}

const _PerProcessFlag_name = "defaulttranslatedmteno_overread"

var _PerProcessFlag_index = [...]uint8{0, 7, 17, 20, 31}

func (i PerProcessFlag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PerProcessFlag_index)-1 {
		return "PerProcessFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PerProcessFlag_name[_PerProcessFlag_index[idx]:_PerProcessFlag_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SystemWideFlagDefault-0]
	_ = x[SystemWideFlagInternalInstall-1]
	_ = x[SystemWideFlagCustomerInstall-2]
	_ = x[SystemWideFlagLockdown-3]
}

const _SystemWideFlag_name = "defaultinternalInstallcustomerInstalllockdown"

var _SystemWideFlag_index = [...]uint8{0, 7, 22, 37, 45}

func (i SystemWideFlag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SystemWideFlag_index)-1 {
		return "SystemWideFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemWideFlag_name[_SystemWideFlag_index[idx]:_SystemWideFlag_index[idx+1]]
}
