// Code generated by "stringer -type=HeaderFileType,HeaderFlag -trimprefix=MH_ -output header_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MH_OBJECT-1]
	_ = x[MH_EXECUTE-2]
	_ = x[MH_FVMLIB-3]
	_ = x[MH_CORE-4]
	_ = x[MH_PRELOAD-5]
	_ = x[MH_DYLIB-6]
	_ = x[MH_DYLINKER-7]
	_ = x[MH_BUNDLE-8]
	_ = x[MH_DYLIB_STUB-9]
	_ = x[MH_DSYM-10]
	_ = x[MH_KEXT_BUNDLE-11]
	_ = x[MH_FILESET-12]
	_ = x[MH_GPU_EXECUTE-13]
	_ = x[MH_GPU_DYLIB-14]
}

const _HeaderFileType_name = "OBJECTEXECUTEFVMLIBCOREPRELOADDYLIBDYLINKERBUNDLEDYLIB_STUBDSYMKEXT_BUNDLEFILESETGPU_EXECUTEGPU_DYLIB"

var _HeaderFileType_index = [...]uint8{0, 6, 13, 19, 23, 30, 35, 43, 49, 59, 63, 74, 81, 92, 101}

func (i HeaderFileType) String() string {
	i -= 1
	if i >= HeaderFileType(len(_HeaderFileType_index)-1) {
		return "HeaderFileType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HeaderFileType_name[_HeaderFileType_index[i]:_HeaderFileType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[NoUndefs-1]
	_ = x[IncrLink-2]
	_ = x[DyldLink-4]
	_ = x[BindAtLoad-8]
	_ = x[Prebound-16]
	_ = x[SplitSegs-32]
	_ = x[LazyInit-64]
	_ = x[TwoLevel-128]
	_ = x[ForceFlat-256]
	_ = x[NoMultiDefs-512]
	_ = x[NoFixPrebinding-1024]
	_ = x[Prebindable-2048]
	_ = x[AllModsBound-4096]
	_ = x[SubsectionsViaSymbols-8192]
	_ = x[Canonical-16384]
	_ = x[WeakDefines-32768]
	_ = x[BindsToWeak-65536]
	_ = x[AllowStackExecution-131072]
	_ = x[RootSafe-262144]
	_ = x[SetuidSafe-524288]
	_ = x[NoReexportedDylibs-1048576]
	_ = x[PIE-2097152]
	_ = x[DeadStrippableDylib-4194304]
	_ = x[HasTLVDescriptors-8388608]
	_ = x[NoHeapExecution-16777216]
	_ = x[AppExtensionSafe-33554432]
	_ = x[NlistOutofsyncWithDyldinfo-67108864]
	_ = x[SimSupport-134217728]
	_ = x[DylibInCache-2147483648]
}

const _HeaderFlag_name = "NoneNoUndefsIncrLinkDyldLinkBindAtLoadPreboundSplitSegsLazyInitTwoLevelForceFlatNoMultiDefsNoFixPrebindingPrebindableAllModsBoundSubsectionsViaSymbolsCanonicalWeakDefinesBindsToWeakAllowStackExecutionRootSafeSetuidSafeNoReexportedDylibsPIEDeadStrippableDylibHasTLVDescriptorsNoHeapExecutionAppExtensionSafeNlistOutofsyncWithDyldinfoSimSupportDylibInCache"

var _HeaderFlag_map = map[HeaderFlag]string{
	0:          _HeaderFlag_name[0:4],
	1:          _HeaderFlag_name[4:12],
	2:          _HeaderFlag_name[12:20],
	4:          _HeaderFlag_name[20:28],
	8:          _HeaderFlag_name[28:38],
	16:         _HeaderFlag_name[38:46],
	32:         _HeaderFlag_name[46:55],
	64:         _HeaderFlag_name[55:63],
	128:        _HeaderFlag_name[63:71],
	256:        _HeaderFlag_name[71:80],
	512:        _HeaderFlag_name[80:91],
	1024:       _HeaderFlag_name[91:106],
	2048:       _HeaderFlag_name[106:117],
	4096:       _HeaderFlag_name[117:129],
	8192:       _HeaderFlag_name[129:150],
	16384:      _HeaderFlag_name[150:159],
	32768:      _HeaderFlag_name[159:170],
	65536:      _HeaderFlag_name[170:181],
	131072:     _HeaderFlag_name[181:200],
	262144:     _HeaderFlag_name[200:208],
	524288:     _HeaderFlag_name[208:218],
	1048576:    _HeaderFlag_name[218:236],
	2097152:    _HeaderFlag_name[236:239],
	4194304:    _HeaderFlag_name[239:258],
	8388608:    _HeaderFlag_name[258:275],
	16777216:   _HeaderFlag_name[275:290],
	33554432:   _HeaderFlag_name[290:306],
	67108864:   _HeaderFlag_name[306:332],
	134217728:  _HeaderFlag_name[332:342],
	2147483648: _HeaderFlag_name[342:354],
}

func (i HeaderFlag) String() string {
	if str, ok := _HeaderFlag_map[i]; ok {
		return str
	}
	return "HeaderFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
