// Code generated by "stringer -type=Platform,Tool,DiceKind -output types_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[macOS-1]
	_ = x[iOS-2]
	_ = x[tvOS-3]
	_ = x[watchOS-4]
	_ = x[bridgeOS-5]
	_ = x[macCatalyst-6]
	_ = x[iOSSimulator-7]
	_ = x[tvOSSimulator-8]
	_ = x[watchOSSimulator-9]
	_ = x[driverKit-10]
	_ = x[firmware-13]
	_ = x[sepOS-14]
}

const (
	_Platform_name_0 = "unknownmacOSiOStvOSwatchOSbridgeOSmacCatalystiOSSimulatortvOSSimulatorwatchOSSimulatordriverKit"
	_Platform_name_1 = "firmwaresepOS"
)

var (
	_Platform_index_0 = [...]uint8{0, 7, 12, 15, 19, 26, 34, 45, 57, 70, 86, 95}
	_Platform_index_1 = [...]uint8{0, 8, 13}
)

func (i Platform) String() string {
	switch {
	case i <= 10:
		return _Platform_name_0[_Platform_index_0[i]:_Platform_index_0[i+1]]
	case 13 <= i && i <= 14:
		i -= 13
		return _Platform_name_1[_Platform_index_1[i]:_Platform_index_1[i+1]]
	default:
		return "Platform(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[clang-1]
	_ = x[swift-2]
	_ = x[ld-3]
	_ = x[lld-4]
}

const _Tool_name = "noneclangswiftldlld"

var _Tool_index = [...]uint8{0, 4, 9, 14, 16, 19}

func (i Tool) String() string {
	if i >= Tool(len(_Tool_index)-1) {
		return "Tool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tool_name[_Tool_index[i]:_Tool_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindData-1]
	_ = x[KindJumpTable8-2]
	_ = x[KindJumpTable16-3]
	_ = x[KindJumpTable32-4]
	_ = x[KindAbsJumpTable32-5]
}

const _DiceKind_name = "KindDataKindJumpTable8KindJumpTable16KindJumpTable32KindAbsJumpTable32"

var _DiceKind_index = [...]uint8{0, 8, 22, 37, 52, 70}

func (i DiceKind) String() string {
	i -= 1
	if i >= DiceKind(len(_DiceKind_index)-1) {
		return "DiceKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DiceKind_name[_DiceKind_index[i]:_DiceKind_index[i+1]]
}
