// Code generated by "stringer -type NecessaryBindingsKind -output capture_string.go"; DO NOT EDIT.

package swift

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PartialApply-0]
	_ = x[AsyncFunction-1]
}

const _NecessaryBindingsKind_name = "PartialApplyAsyncFunction"

var _NecessaryBindingsKind_index = [...]uint8{0, 12, 25}

func (i NecessaryBindingsKind) String() string {
	if i >= NecessaryBindingsKind(len(_NecessaryBindingsKind_index)-1) {
		return "NecessaryBindingsKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NecessaryBindingsKind_name[_NecessaryBindingsKind_index[i]:_NecessaryBindingsKind_index[i+1]]
}
