// Code generated by "stringer -type ContextDescriptorKind,TypeReferenceKind,MetadataInitializationKind -trimprefix=MetadataInit -output types_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Module-0]
	_ = x[Extension-1]
	_ = x[Anonymous-2]
	_ = x[Protocol-3]
	_ = x[OpaqueType-4]
	_ = x[Class-16]
	_ = x[Struct-17]
	_ = x[Enum-18]
}

const (
	_ContextDescriptorKind_name_0 = "ModuleExtensionAnonymousProtocolOpaqueType"
	_ContextDescriptorKind_name_1 = "ClassStructEnum"
)

var (
	_ContextDescriptorKind_index_0 = [...]uint8{0, 6, 15, 24, 32, 42}
	_ContextDescriptorKind_index_1 = [...]uint8{0, 5, 11, 15}
)

func (i ContextDescriptorKind) String() string {
	switch {
	case i <= 4:
		return _ContextDescriptorKind_name_0[_ContextDescriptorKind_index_0[i]:_ContextDescriptorKind_index_0[i+1]]
	case 16 <= i && i <= 18:
		i -= 16
		return _ContextDescriptorKind_name_1[_ContextDescriptorKind_index_1[i]:_ContextDescriptorKind_index_1[i+1]]
	default:
		return "ContextDescriptorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectTypeDescriptor-0]
	_ = x[IndirectTypeDescriptor-1]
	_ = x[DirectObjCClassName-2]
	_ = x[IndirectObjCClass-3]
}

const _TypeReferenceKind_name = "DirectTypeDescriptorIndirectTypeDescriptorDirectObjCClassNameIndirectObjCClass"

var _TypeReferenceKind_index = [...]uint8{0, 20, 42, 61, 78}

func (i TypeReferenceKind) String() string {
	if i >= TypeReferenceKind(len(_TypeReferenceKind_index)-1) {
		return "TypeReferenceKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeReferenceKind_name[_TypeReferenceKind_index[i]:_TypeReferenceKind_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetadataInitNone-0]
	_ = x[MetadataInitSingleton-1]
	_ = x[MetadataInitForeign-2]
}

const _MetadataInitializationKind_name = "NoneSingletonForeign"

var _MetadataInitializationKind_index = [...]uint8{0, 4, 13, 20}

func (i MetadataInitializationKind) String() string {
	if i >= MetadataInitializationKind(len(_MetadataInitializationKind_index)-1) {
		return "MetadataInitializationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MetadataInitializationKind_name[_MetadataInitializationKind_index[i]:_MetadataInitializationKind_index[i+1]]
}
