// Code generated by "stringer -type=CDKind -output types_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Module-0]
	_ = x[Extension-1]
	_ = x[Anonymous-2]
	_ = x[Protocol-3]
	_ = x[OpaqueType-4]
	_ = x[Class-16]
	_ = x[Struct-17]
	_ = x[Enum-18]
}

const (
	_CDKind_name_0 = "ModuleExtensionAnonymousProtocolOpaqueType"
	_CDKind_name_1 = "ClassStructEnum"
)

var (
	_CDKind_index_0 = [...]uint8{0, 6, 15, 24, 32, 42}
	_CDKind_index_1 = [...]uint8{0, 5, 11, 15}
)

func (i CDKind) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _CDKind_name_0[_CDKind_index_0[i]:_CDKind_index_0[i+1]]
	case 16 <= i && i <= 18:
		i -= 16
		return _CDKind_name_1[_CDKind_index_1[i]:_CDKind_index_1[i+1]]
	default:
		return "CDKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
