name: Swift Package

on: [push]

jobs:
  build:
    name: Build and test package
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
