package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	defPath = flag.String("def", "StandardTypesMangling.def", "path to StandardTypesMangling.def")
	outPath = flag.String("out", "standard_types_generated.go", "output file path")
)

type category int

const (
	categoryStandard category = iota
	categoryConcurrency
)

type entry struct {
	mangling string
	typeName string
	cat      category
}

var (
	stdRegex         = regexp.MustCompile(`^STANDARD_TYPE\(\s*[^,]+,\s*([^,]+),\s*([^)]+)\)`)
	concurrencyRegex = regexp.MustCompile(`^STANDARD_TYPE_CONCURRENCY\(\s*[^,]+,\s*([^,]+),\s*([^)]+)\)`)
	objcRegex        = regexp.MustCompile(`^OBJC_INTEROP_STANDARD_TYPE\(\s*[^,]+,\s*([^,]+),\s*([^)]+)\)`)
)

func main() {
	flag.Parse()

	entries, err := parseEntries(*defPath)
	if err != nil {
		fatal(err)
	}

	if err := writeOutput(entries, *outPath); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "genstandardtypes: %v\n", err)
	os.Exit(1)
}

func parseEntries(path string) ([]entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var entries []entry
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "//") || strings.HasPrefix(line, "#") {
			continue
		}

		switch {
		case stdRegex.MatchString(line):
			matches := stdRegex.FindStringSubmatch(line)
			if len(matches) < 3 || matches[1] == "MANGLING" {
				continue
			}
			entries = append(entries, entry{
				mangling: matches[1],
				typeName: matches[2],
				cat:      categoryStandard,
			})
		case objcRegex.MatchString(line):
			matches := objcRegex.FindStringSubmatch(line)
			if len(matches) < 3 || matches[1] == "MANGLING" {
				continue
			}
			entries = append(entries, entry{
				mangling: matches[1],
				typeName: matches[2],
				cat:      categoryStandard,
			})
		case concurrencyRegex.MatchString(line):
			matches := concurrencyRegex.FindStringSubmatch(line)
			if len(matches) < 3 || matches[1] == "MANGLING" {
				continue
			}
			entries = append(entries, entry{
				mangling: matches[1],
				typeName: matches[2],
				cat:      categoryConcurrency,
			})
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

func writeOutput(entries []entry, outFile string) error {
	var (
		standard    = make(map[string]string)
		concurrency = make(map[string]string)
	)

	for _, e := range entries {
		fullName := "Swift." + e.typeName
		switch e.cat {
		case categoryStandard:
			standard[e.mangling] = fullName
		case categoryConcurrency:
			concurrency[e.mangling] = fullName
		}
	}

	var builder strings.Builder
	builder.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	builder.WriteString("package swift\n\n")

	writeMap := func(varName string, data map[string]string) {
		keys := make([]string, 0, len(data))
		for k := range data {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		builder.WriteString(fmt.Sprintf("var %s = map[string]string{\n", varName))
		for _, k := range keys {
			builder.WriteString(fmt.Sprintf("\t%q: %q,\n", k, data[k]))
		}
		builder.WriteString("}\n\n")
	}

	writeMap("MangledKnownTypeKind", standard)
	writeMap("MangledKnownTypeKind2", concurrency)

	dir := filepath.Dir(outFile)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	return os.WriteFile(outFile, []byte(builder.String()), 0o644)
}
