// Code generated by "stringer -type ProtocolContextDescriptorFlags -output types_string.go"; DO NOT EDIT.

package protocols

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HasClassConstraint-0]
	_ = x[HasClassConstraint_width-1]
	_ = x[IsResilient-1]
	_ = x[SpecialProtocolKind-2]
	_ = x[SpecialProtocolKind_width-6]
}

const (
	_ProtocolContextDescriptorFlags_name_0 = "HasClassConstraintHasClassConstraint_widthSpecialProtocolKind"
	_ProtocolContextDescriptorFlags_name_1 = "SpecialProtocolKind_width"
)

var (
	_ProtocolContextDescriptorFlags_index_0 = [...]uint8{0, 18, 42, 61}
)

func (i ProtocolContextDescriptorFlags) String() string {
	switch {
	case i <= 2:
		return _ProtocolContextDescriptorFlags_name_0[_ProtocolContextDescriptorFlags_index_0[i]:_ProtocolContextDescriptorFlags_index_0[i+1]]
	case i == 6:
		return _ProtocolContextDescriptorFlags_name_1
	default:
		return "ProtocolContextDescriptorFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
