// Code generated by "stringer -type ProtocolContextDescriptorFlags,GRKind,PRKind -trimprefix=GRKind -output types_string.go"; DO NOT EDIT.

package protocols

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HasClassConstraint-0]
	_ = x[HasClassConstraint_width-1]
	_ = x[IsResilient-1]
	_ = x[SpecialProtocolKind-2]
	_ = x[SpecialProtocolKind_width-6]
}

const (
	_ProtocolContextDescriptorFlags_name_0 = "HasClassConstraintHasClassConstraint_widthSpecialProtocolKind"
	_ProtocolContextDescriptorFlags_name_1 = "SpecialProtocolKind_width"
)

var (
	_ProtocolContextDescriptorFlags_index_0 = [...]uint8{0, 18, 42, 61}
)

func (i ProtocolContextDescriptorFlags) String() string {
	switch {
	case i <= 2:
		return _ProtocolContextDescriptorFlags_name_0[_ProtocolContextDescriptorFlags_index_0[i]:_ProtocolContextDescriptorFlags_index_0[i+1]]
	case i == 6:
		return _ProtocolContextDescriptorFlags_name_1
	default:
		return "ProtocolContextDescriptorFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GRKindProtocol-0]
	_ = x[GRKindSameType-1]
	_ = x[GRKindBaseClass-2]
	_ = x[GRKindSameConformance-3]
	_ = x[GRKindLayout-31]
}

const (
	_GRKind_name_0 = "ProtocolSameTypeBaseClassSameConformance"
	_GRKind_name_1 = "Layout"
)

var (
	_GRKind_index_0 = [...]uint8{0, 8, 16, 25, 40}
)

func (i GRKind) String() string {
	switch {
	case i <= 3:
		return _GRKind_name_0[_GRKind_index_0[i]:_GRKind_index_0[i+1]]
	case i == 31:
		return _GRKind_name_1
	default:
		return "GRKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BaseProtocol-0]
	_ = x[Method-1]
	_ = x[Init-2]
	_ = x[Getter-3]
	_ = x[Setter-4]
	_ = x[ReadCoroutine-5]
	_ = x[ModifyCoroutine-6]
	_ = x[AssociatedTypeAccessFunction-7]
	_ = x[AssociatedConformanceAccessFunction-8]
}

const _PRKind_name = "BaseProtocolMethodInitGetterSetterReadCoroutineModifyCoroutineAssociatedTypeAccessFunctionAssociatedConformanceAccessFunction"

var _PRKind_index = [...]uint8{0, 12, 18, 22, 28, 34, 47, 62, 90, 125}

func (i PRKind) String() string {
	if i >= PRKind(len(_PRKind_index)-1) {
		return "PRKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PRKind_name[_PRKind_index[i]:_PRKind_index[i+1]]
}
